### PR TITLE
Add more

### PR DESCRIPTION
**Pull request by lisa**
*chans, kf and begin the propaganda section.

Signed-off-by: Lisa Seelye <lisa@users.noreply.github.com>

### CODE REVIEW

**Comment by lisa** [comment]
Sorry, this shouldn't have been a PR.

**Comment by chigh** [comment]
That's okay. I think I _do_ need to add them.
If by kf, you mean kiwifarms. that's in there.. at least the input file.

**Comment by lisa** [comment]
It is, yeah. I just fixed my fork :) There's a .nl and .pl for them which I've added to my fork as well ([source](https://www.dailydot.com/debug/kiwi-farms-down-ddos/)). I hesitate to submit a PR upstream since I have added fox news as a propaganda hate site and that might not be so welcome here.

**Comment by chigh** [comment]
Ah, I didn't know about the nl and pl for them. I am mostly going by SPLC and a few Canadian mentions. So, I haven't added Fox News, but I don't disagree.

**Comment by chigh** [comment]
@lisa FYI, I just went through most of the 2018 list from SPLC's map and made some pretty significant updates. I'm going through each category and pushing them.

**Pull request closed without merging**
